### ISSUE TITLE
주어로 시작하는 문장을 번역하면 어색해요

### ISSUE THREAD

**Issue by asunhs** [MordernProgramming/milewski-ctfp-pdf#1]
https://github.com/MordernProgramming/milewski-ctfp-pdf/blob/314fa0742f94b8fcab1f193053a7b1bcd020ea4a/src/content/1.4/kleisli-categories.tex#L21-L23

```최근의 프로그래밍에서 (우리는?) 복잡한 동시성을 다루기에 가능한 한 전역 상태를 변경하는 것을 기피합니다.```

어떻게 생각하세요? ㅋㅋㅋ

**Comment by ueong** [comment]
여기서는 문맥 상 '우리는'이 안 들어가는게 좋은 것 같은데요.
저 같으면 '현대 프로그래밍에서는 동시성 제어의 복잡성 때문에 가능하면 변경될 수 있는 전역 상태를 가지지 않으려고 합니다.' 정도로 의역할 것 같아요.

**Comment by asunhs** [comment]
이 문장에 대한 의견은 좋은 것 같아요. 그 전에 얘기 나눠보고 싶은건 이 문장 외에도 의외로 주어로 문장을 시작하는 경우가 많은데, 우리말 문장엔 그런 경우가 어색한거 같아서 여쭸어요.

**Comment by caffeinee** [comment]
저는 의미가 정확하게 전달될 수 있다고 하면 자연스럽게 의역하는 것을 더 선호하는 편입니다.
개인적으로는 수동태 문장도 (주어가 없는) 능동태로 변환하는 것도 괜찮다고 생각합니다.

**Comment by asunhs** [comment]
> 개인적으로는 수동태 문장도 (주어가 없는) 능동태로 변환하는 것도 괜찮다고 생각합니다.

저도 이 부분은 노력해볼께요
